title: SaaS Passport
description: adaptable standard terms for software as a service
url: https://saaspassport.org
homepage: https://saaspassport.org
github:
  org: https://github.com/saaspassport
  forms: https://github.com/saaspassport/saaspassport
  website: https://github.com/saaspassport/saaspassport.com
defaults:
  - scope:
      type: pages
    values:
      layout: default
exclude:
  - README.md
